# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 02:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LanguageExchange', '0002_auto_20170320_0133'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='status_message',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
