# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 02:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LanguageExchange', '0005_myuser_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='Likes',
        ),
    ]
